### ISSUE TITLE
曝光事件没有回调？

### ISSUE THREAD

**Issue by PaulZJ** [sanyuankexie/Gbox#27]
![image](https://user-images.githubusercontent.com/5515574/69798319-12a60880-120c-11ea-9150-e0f85e31c6c2.png)

第一个断点进了；第二个断点一直没进去；点击事件ok，就是曝光有问题；
啥原因？

**Comment by LukeXeon** [comment]
抱歉，最近要考试了，所以比较忙没时间看，我会在12月下旬跟进这个问题。

**Comment by LukeXeon** [comment]
额，解释一下为什么会出现上面的情况：
简单来讲，就是曝光时机已经过了，在使用Live reload的时候其实你看到的Component可能已经触发过曝光事件了，所以在你写onVisible属性的时候，只是更换了EventHandler，所以不会再次触发可见事件，正常使用是没啥问题的。
我会想办法处理Live Reload时候的特殊情况，所以这个问题我先关闭了。
