### ISSUE TITLE
你好，我有三个小问题想请教！

### ISSUE THREAD

**Issue by spysoos** [sanyuankexie/Gbox#47]
1. “包括数学运算，for语句，三元表达式，简单的java方法调用” 这里的java调用是指什么?能说说应用场景吗？和Databinding里的一样吗？
2.Native 节点是不是只是包一个原生空间进去，能对该原生控件进行赋值变量或者操作吗？
3. 360 能修改吗？
谢谢！

**Comment by LukeXeon** [comment]
1，你可以克隆项目到本地然后编译playground模块，这是一个预览app，上面有很多样例，你点击任意一个Item会直接弹出源码让你查看，但是它还没有完成
下面是banner的代码，它包含for语句
`<?xml version="1.0" encoding="utf-8"?>
<Flex
    background="#7c4dff"
    alignItems="center"
    justifyContent="center"
    width="360">
    <Banner
        marginTop="10"
        marginBottom="5"
        height="150"
        width="340">
        <for var="index" from="0" to="${urls.size()-1}">
            <Flex
                clickUrl="${url}">
                <Image
                    borderRadius="12"
                    flexGrow="1"
                    scaleType="fitXY"
                    url="${urls[index]}" />
            </Flex>
        </for>
    </Banner>
</Flex>`
更复杂的布局请查看，它包含for和三元表达式，由于太长我就不贴了
[multi_images.flexml](https://github.com/sanyuankexie/Gbox/blob/master/playground/src/main/assets/layout/homepage/feeds/multi_images.flexml)

2，Native节点兼容性太差...已经弃用
3，360现在是硬编码的，但是可以改的，并且提供dp和sp的转换函数

注：近期我会发布新版本，是一个大版本更新，会加入以下功能：
1，新的IDEA（AS）插件，补全等
2，新的mock工具，与IDEA（AS）更好的配合

**Comment by spysoos** [comment]
期待！
请问 下一版本有发版的大概时间吗？

**Comment by LukeXeon** [comment]
新版本已经在github发布，你可以在release界面下载playground apk先看看效果，但是文档还莫得……文档我还得写，近期我会在掘金发。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: spysoos <notifications@github.com&gt;
发送时间: 2020年2月20日 10:05
收件人: sanyuankexie/Flexml <Flexml@noreply.github.com&gt;
抄送: Luke <imlkluo@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[sanyuankexie/Flexml] 你好，我有三个小问题想请教！ (#47)




期待！
 请问 下一版本有发版的大概时间吗？
